name: claims_analytics
version: '1.0.0'
config-version: 2

profile: claims_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  claims_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
